@startuml
actor User
participant ATMSystem

User -> ATMSystem: login()
alt Authentication Success
    ATMSystem -> User: Authentication Success
    User -> ATMSystem: checkBalance()
    ATMSystem -> User: Show Balance in THB and BTC
else Authentication Failed
    ATMSystem -> User: Authentication Failed
end

destroy User
destroy ATMSystem
@enduml
